name: Deploy Documentation

on:
  push:
    branches:
      - test-github-action
  # workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: docs/mlc-config.json
        folder-path: docs

  build-and-deploy-docs:
    needs: [markdown-link-check]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install Documentation Dependencies
        run: |
          source venv/bin/activate
          pip install -r docs/requirements.txt

      - name: Verify Installed Packages
        run: |
          source venv/bin/activate
          echo "Verifying installed dependencies..."
          pip list | grep -E 'mkdocs'

      - name: Build documentation
        run: |
          source venv/bin/activate
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          folder: site
          user_name: 'GitHub Action'
          user_email: 'action@github.com'
          commit_message: 'Deploy documentation'